Repository sharkdp/bat, pull requests merged in 2019-10, with the labels that each got.

#674 Ensure submodules are updated before creating asset cache
  assets/create.sh
Labels: packaging/tooling

#703 Add syntax highlighting for /etc/resolv.conf
  assets/syntaxes/Resolv.sublime-syntax
Labels: new-syntax

#696 Add fstab syntax definitions
  assets/syntaxes/Fstab.sublime-syntax
Labels: new-syntax

#705 doc: Add Ubuntu/Debian bat package to Readme
  README.md
Labels: documentation

#700 Update options sort order in --help and manpage file
  assets/manual/bat.1.in
  src/bin/bat/clap_app.rs
Labels: documentation
